version: '3.7'

services:
  postgres:
    image: postgres:13.3
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: currency

  scheduler:
    image: currency-service:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/currency
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - CURRENCY_API_URL=https://alfabank.ru/api/v1/scrooge/currencies/alfa-rates
      - CURRENCY_CODES:USD,EUR,GBP
      - CURRENCY_RATE_TYPE:makeCash
      - CURRENCY_LAST_ACTUAL_FOR_DATE:true
      - CURRENCY_CLIENT_TYPE:standardCC


  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
